export const CATEGORY_INFO: Record<string, string> = {
  aadhaar_authentication:              'Aadhaar-enabled transactions',
  acp_disbursement_agri:               'ACP disbursement - Agriculture',
  acp_disbursement_msme:               'ACP disbursement - MSME',
  acp_disbursement_non_ps:             'ACP disbursement - Non-Priority Sector',
  acp_disbursement_other_ps:           'ACP disbursement - Other Priority Sector',
  acp_npa_outstanding:                 'ACP NPA outstanding',
  acp_priority_sector_os_npa:          'Priority sector outstanding & NPA',
  acp_target_achievement:              'ACP targets vs achievement',
  agri_npa:                            'Agriculture NPA',
  agri_outstanding:                    'Agriculture outstanding',
  branch_network:                      'Bank branches, ATMs, CSPs',
  credit_deposit_ratio:                'Deposits, advances, CD ratio',
  crop_insurance:                      'Crop insurance (PMFBY)',
  dcc_meetings:                        'DCC/DLRC meetings',
  digital_transactions:                'Digital transactions (UPI, IMPS, BHIM)',
  education_loan:                      'Education loans',
  fi_kcc:                              'FI & KCC progress',
  flc_report:                          'Financial Literacy Centre report',
  fi_village_banking:                  'Village banking outlets',
  govt_sponsored_npa:                  'Government sponsored schemes NPA',
  housing_pmay:                        'Housing loans / PMAY',
  investment_credit_agri_disbursement: 'Investment credit (agri) - disbursement',
  investment_credit_agri_outstanding:  'Investment credit (agri) - outstanding',
  jlg:                                 'Joint Liability Groups',
  kcc:                                 'Kisan Credit Card',
  kcc_crop:                            'KCC crop-wise details',
  ldm_details:                         'Lead District Manager details',
  minority:                             'Lending to minorities',
  minority_disbursement:               'Lending to minorities - disbursement',
  minority_outstanding:                'Lending to minorities - outstanding',
  msme_npa:                            'MSME NPA',
  msme_outstanding:                    'MSME outstanding',
  non_ps_npa:                          'Non-Priority Sector NPA',
  non_ps_outstanding:                  'Non-Priority Sector outstanding',
  nrlm:                                'National Rural Livelihoods Mission',
  nulm:                                'National Urban Livelihoods Mission',
  other_ps_npa:                        'Other Priority Sector NPA',
  other_ps_outstanding:                'Other Priority Sector outstanding',
  pmegp:                               'PM Employment Generation Programme',
  pmjdy:                               'PM Jan Dhan Yojana',
  pmmy_mudra_disbursement:             'PMMY/Mudra disbursement',
  pmfme:                               'PM Formalisation of Micro Food Enterprises',
  pmmy_mudra_os_npa:                   'PMMY/Mudra outstanding & NPA',
  priority_sector_analysis:            'Priority sector lending analysis',
  recovery_bakijai:                    'Recovery & Bakijai',
  rseti:                               'Rural Self Employment Training',
  sc_st_finance:                       'Lending to SC/ST',
  shg:                                 'Self Help Groups',
  social_security:                     'Social security (PMSBY, PMJJBY, APY)',
  sui:                                 'Stand Up India',
  segregation_advances:                'Segregation of advances',
  tea_garden_labourers:                'Tea garden labourers',
  uncategorized:                       'Other / Uncategorized',
  weaker_section_os:                   'Weaker section lending',
  women_finance:                       'Lending to women',
  // West Bengal specific categories
  acp_priority_sector:                 'ACP Priority Sector targets & achievement',
  aif:                                 'Agriculture Infrastructure Fund',
  apy:                                 'Atal Pension Yojana',
  digital_payments:                    'Digital payments ecosystem',
  financial_literacy:                  'Financial Literacy Centres & camps',
  kcc_animal_husbandry:                'KCC Animal Husbandry',
  kcc_fishery:                         'KCC Fishery',
  mudra:                               'MUDRA loans (Shishu, Kishor, Tarun)',
  msme:                                'MSME clusters & credit linkage',
  nlm:                                 'National Livestock Mission',
  npa_recovery:                        'NPA & recovery position',
  sarfaesi:                            'SARFAESI recovery',
  shg_nrlm:                            'SHG credit linkage (NRLM)',
  shg_nulm:                            'SHG credit linkage (NULM)',
  social_security_schemes:             'Social security schemes (PMJJBY, PMSBY, APY)',
  svskp:                               'Swarnjayanti Gram Swarozgar Yojana',
  farm_sector:                         'Farm sector lending',
  non_farm_sector:                     'Non-farm sector lending',
  weaker_section:                      'Weaker section lending',
  housing_loan:                        'Housing loans',
  // Jharkhand specific categories
  acp_disbursement_agri_p2:            'ACP Agri disbursement (contd.)',
  acp_disbursement_non_ps:             'ACP Non-PS disbursement',
  acp_disbursement_non_ps_p2:          'ACP Non-PS disbursement (contd.)',
  acp_disbursement_other_ps_p2:        'ACP Other PS disbursement (contd.)',
  acp_disbursement_other_ps_p3:        'ACP Other PS disbursement (contd. 3)',
  ads_progress:                        'Advance Data System progress',
  agri_npa_p2:                         'Agriculture NPA (contd.)',
  business_correspondents:             'Business Correspondents',
  doubling_farmers_income:             'Doubling Farmers Income',
  doubling_farmers_income_p2:          'Doubling Farmers Income (contd.)',
  doubling_farmers_income_p3:          'Doubling Farmers Income (contd. 3)',
  govt_sponsored_npa:                  'Govt Sponsored Schemes NPA',
  guruji_credit_card:                  'Guruji Credit Card',
  investment_utilization:              'Investment / Place of Utilization',
  npa_recovery_p2:                     'NPA recovery (contd.)',
  other_ps_npa:                        'Other Priority Sector NPA',
  pm_svanidhi:                         'PM SVANidhi',
  pm_svanidhi_p2:                      'PM SVANidhi (contd.)',
  pm_vishwakarma:                      'PM Vishwakarma',
  pmmy_mudra_disbursement:             'PMMY/Mudra disbursement',
  pmmy_mudra_os_npa:                   'PMMY/Mudra O/S & NPA',
  priority_sector_npa:                 'Priority Sector NPA',
  priority_sector_outstanding:         'Priority Sector outstanding',
  recovery_certificate:                'Certificate Cases recovery',
  recovery_drt:                        'DRT Cases recovery',
  rseti_p2:                            'RSETI (contd.)',
  sc_st_finance_p2:                    'SC/ST finance (contd.)',
  shg_p2:                              'SHG (contd.)',
  shg_p3:                              'SHG (contd. 3)',
  women_finance_p2:                    'Women finance (contd.)',
  // Odisha specific categories
  acp_district_agri:                   'ACP District-wise Agriculture',
  acp_district_agri_allied:            'ACP District-wise Agri & Allied',
  acp_district_ancillary:              'ACP District-wise Ancillary',
  acp_district_msme:                   'ACP District-wise MSME',
  acp_district_total:                  'ACP District-wise Total',
  bharatnet:                           'BharatNet connectivity',
  bharatnet_p2:                        'BharatNet (contd.)',
  bharatnet_p3:                        'BharatNet (contd. 3)',
  bharatnet_p4:                        'BharatNet (contd. 4)',
  branch_network_p2:                   'Branch network (contd.)',
  branch_network_p3:                   'Branch network (contd. 3)',
  branch_network_p4:                   'Branch network (contd. 4)',
  cgtmse:                              'CGTMSE coverage',
  cgtmse_p2:                           'CGTMSE (contd.)',
  cm_srim:                             'CM SRIM scheme',
  digital_coverage_business:           'Digital coverage - business accounts',
  digital_coverage_savings:            'Digital coverage - savings accounts',
  digital_coverage_savings_p2:         'Digital coverage - savings (contd.)',
  digital_coverage_savings_p3:         'Digital coverage - savings (contd. 3)',
  digital_coverage_savings_p4:         'Digital coverage - savings (contd. 4)',
  district_misc:                       'District miscellaneous data',
  key_indicators:                      'Key indicators (CD ratio, deposits, advances)',
  npa:                                 'Non-Performing Assets',
  pm_surya_ghar:                       'PM Surya Ghar',
  pmjdy_p2:                            'PMJDY (contd.)',
  pmjdy_p3:                            'PMJDY (contd. 3)',
  pmjdy_p4:                            'PMJDY (contd. 4)',
  rseti_p3:                            'RSETI (contd. 3)',
  rseti_p4:                            'RSETI (contd. 4)',
  rseti_p5:                            'RSETI (contd. 5)',
  rseti_p6:                            'RSETI (contd. 6)',
  social_security_claims:              'Social security claims',
  stand_up_india:                      'Stand Up India',
  stand_up_india_p2:                   'Stand Up India (contd.)',
  suy:                                 'SUY scheme',
  town_hall_msme:                      'Town Hall MSME',
  // Chhattisgarh specific categories
  atm_network:                         'ATM network (district-wise)',
};

// Category descriptions for tooltips
export const CATEGORY_DESCRIPTIONS: Record<string, string> = {
  credit_deposit_ratio: 'Ratio of bank credit to deposits. Below 40% means the district is credit-starved — deposits flow out to fund lending elsewhere.',
  key_indicators: 'Summary of deposits, advances, and CD ratio across all bank branches in the district.',
  branch_network: 'Physical banking infrastructure — bank branches (rural/semi-urban/urban), ATMs, and Business Correspondent outlets.',
  pmjdy: 'PM Jan Dhan Yojana — zero-balance bank accounts for the unbanked. Tracks accounts, Aadhaar seeding, RuPay cards, and zero-balance dormancy.',
  digital_transactions: 'Coverage of digital payment modes (UPI, IMPS, cards, USSD) across savings bank accounts. Measures digital readiness, not transaction volume.',
  aadhaar_authentication: 'Aadhaar linkage and biometric authentication across bank accounts (CASA). Required for DBT, AePS, and eKYC.',
  fi_village_banking: 'Banking outlet coverage at the village level — how many villages have a bank branch, BC, or ATM within 5 km.',
  kcc: 'Kisan Credit Card — revolving credit for farmers at 4% effective interest. Covers crop production, animal husbandry, and fisheries.',
  kcc_crop: 'KCC breakdowns by crop type — new issuances, renewals, NPA, and active cards for crops, animal husbandry, and fisheries.',
  fi_kcc: 'FI-focused KCC progress — issuance targets, achievement, and Aadhaar authentication of KCC holders.',
  shg: 'Self Help Groups — savings-linked and credit-linked SHGs under the SHG-Bank Linkage Programme. Tracks outstanding loans and NPA.',
  shg_nrlm: 'SHG credit linkage under National Rural Livelihoods Mission (NRLM/DAY-NRLM).',
  jlg: 'Joint Liability Groups — small farmer groups (4-10 members) who guarantee each other\'s loans. Common for tenant farmers without land titles.',
  nrlm: 'National Rural Livelihoods Mission — SHG formation, bank linkage, and livelihood support for rural poor.',
  crop_insurance: 'PM Fasal Bima Yojana (PMFBY) — crop insurance enrollment, coverage, and claims by district.',
  social_security: 'PM Suraksha Bima (PMSBY), PM Jeevan Jyoti Bima (PMJJBY), and Atal Pension Yojana (APY) enrollment.',
  pmegp: 'PM Employment Generation Programme — micro-enterprise loans with 25-35% subsidy for setting up new units.',
  sui: 'Stand Up India — loans of ₹10L-1Cr to SC/ST and women entrepreneurs for greenfield enterprises.',
  pmmy_mudra_disbursement: 'PM Mudra Yojana — micro-enterprise loans in 3 tiers: Shishu (up to ₹50K), Kishore (₹50K-5L), Tarun (₹5L-10L).',
  pmmy_mudra_os_npa: 'Mudra loan outstanding and NPA position — tracks repayment health of micro-enterprise loans.',
  housing_pmay: 'PM Awas Yojana (PMAY) — housing loans and subsidies for economically weaker sections.',
  education_loan: 'Education loans and other priority/non-priority sector lending breakdowns.',
  acp_disbursement_agri: 'Annual Credit Plan — agriculture sector disbursement targets and achievement.',
  acp_disbursement_msme: 'Annual Credit Plan — MSME sector disbursement by enterprise size (Micro/Small/Medium) and loan type (Term Loan/Working Capital).',
  acp_disbursement_other_ps: 'Annual Credit Plan — other priority sector disbursement (education, housing, renewable energy, social infrastructure).',
  acp_disbursement_non_ps: 'Annual Credit Plan — non-priority sector lending (personal loans, housing above threshold, etc.).',
  acp_target_achievement: 'Annual Credit Plan targets vs actual achievement across priority sector categories.',
  minority_disbursement: 'Lending to minority communities — disbursement during current year.',
  minority_outstanding: 'Lending to minority communities — outstanding loans and NPA.',
  sc_st_finance: 'Lending to Scheduled Caste and Scheduled Tribe borrowers.',
  weaker_section_os: 'Lending to weaker sections — small/marginal farmers, artisans, SHGs, SC/ST, minorities.',
  women_finance: 'Lending to women borrowers and women-headed enterprises.',
  rseti: 'Rural Self Employment Training Institutes — training programs and settlement rates for rural youth.',
  nulm: 'National Urban Livelihoods Mission — SHG formation, skill training, and self-employment support in urban areas.',
  dcc_meetings: 'District Consultative Committee / District Level Review Committee meeting details.',
  agri_outstanding: 'Agriculture sector — outstanding loans position.',
  agri_npa: 'Agriculture sector — Non-Performing Assets (loans overdue 90+ days).',
  msme_outstanding: 'MSME sector — outstanding loans position.',
  msme_npa: 'MSME sector — Non-Performing Assets.',
  acp_priority_sector_os_npa: 'Priority sector outstanding loans and NPA across agriculture, MSME, and other PS categories.',
  investment_credit_agri_disbursement: 'Investment credit for agriculture — term loans for farm mechanization, irrigation, land development.',
  investment_credit_agri_outstanding: 'Investment credit for agriculture — outstanding position.',
};

// Category tiers for grouping in UI (most important first)
export const CATEGORY_TIERS: Record<string, string[]> = {
  'Core Financial Inclusion': [
    'credit_deposit_ratio', 'key_indicators',
    'branch_network', 'branch_network_p2', 'branch_network_p3', 'branch_network_p4',
    'business_correspondents', 'atm_network',
    'pmjdy', 'pmjdy_p2', 'pmjdy_p3', 'pmjdy_p4',
    'digital_transactions', 'digital_payments', 'digital_coverage_savings',
    'digital_coverage_savings_p2', 'digital_coverage_savings_p3', 'digital_coverage_savings_p4',
    'digital_coverage_business',
    'aadhaar_authentication',
    'fi_village_banking',
  ],
  'Agriculture & Rural Credit': [
    'kcc', 'kcc_crop', 'fi_kcc',
    'kcc_animal_husbandry', 'kcc_fishery', 'kcc_fisheries',
    'shg', 'shg_nrlm', 'shg_p2', 'shg_p3',
    'jlg', 'nrlm',
    'crop_insurance',
    'acp_disbursement_agri', 'acp_disbursement_agri_p2',
    'investment_credit_agri_disbursement', 'investment_credit_agri_outstanding',
    'agri_outstanding', 'agri_npa', 'agri_npa_p2',
    'farm_sector',
  ],
  'Government Schemes': [
    'social_security', 'social_security_schemes', 'social_security_claims', 'social_security_2',
    'pmegp', 'sui', 'stand_up_india', 'stand_up_india_p2',
    'pmmy_mudra_disbursement', 'pmmy_mudra_os_npa', 'mudra',
    'housing_pmay', 'housing_loan',
    'nulm', 'shg_nulm',
    'rseti', 'rseti_p2', 'rseti_p3', 'rseti_p4', 'rseti_p5', 'rseti_p6',
    'pm_svanidhi', 'pm_svanidhi_p2', 'pm_vishwakarma', 'pm_surya_ghar',
    'pmfme', 'aif',
  ],
  'MSME & Priority Sector': [
    'acp_disbursement_msme',
    'msme_outstanding', 'msme_npa', 'msme',
    'acp_disbursement_other_ps', 'acp_disbursement_other_ps_p2', 'acp_disbursement_other_ps_p3',
    'acp_disbursement_non_ps', 'acp_disbursement_non_ps_p2',
    'acp_priority_sector_os_npa', 'acp_priority_sector', 'acp_target_achievement',
    'acp_npa_outstanding',
    'other_ps_outstanding', 'other_ps_npa',
    'non_ps_outstanding', 'non_ps_npa',
    'priority_sector_analysis', 'priority_sector_npa', 'priority_sector_outstanding',
    'education_loan',
    'minority', 'minority_disbursement', 'minority_outstanding',
    'sc_st_finance', 'sc_st_finance_p2',
    'weaker_section_os', 'weaker_section',
    'women_finance', 'women_finance_p2',
    'non_farm_sector',
    'cgtmse', 'cgtmse_p2',
  ],
  'Other': [
    'dcc_meetings', 'ldm_details', 'flc_report', 'financial_literacy',
    'uncategorized', 'govt_sponsored_npa',
    'recovery_bakijai', 'npa_recovery', 'npa_recovery_p2', 'npa', 'sarfaesi',
    'recovery_certificate', 'recovery_drt',
    'segregation_advances', 'tea_garden_labourers',
    'ads_progress', 'bharatnet', 'bharatnet_p2', 'bharatnet_p3', 'bharatnet_p4',
    'district_misc', 'guruji_credit_card', 'nlm', 'svskp', 'suy',
    'cm_srim', 'town_hall_msme', 'investment_utilization',
    'doubling_farmers_income', 'doubling_farmers_income_p2', 'doubling_farmers_income_p3',
    'apy', 'acp_district_agri', 'acp_district_agri_allied', 'acp_district_ancillary',
    'acp_district_msme', 'acp_district_total',
  ],
};

// Get tier for a category
export function getCategoryTier(cat: string): string {
  for (const [tier, cats] of Object.entries(CATEGORY_TIERS)) {
    if (cats.includes(cat)) return tier;
  }
  return 'Other';
}

export const QUARTER_ORDER = [
  'june_2020','sept_2020','dec_2020',
  'june_2021','sept_2021','dec_2021',
  'mar_2022','june_2022','sept_2022','dec_2022',
  'mar_2023','june_2023','sept_2023','dec_2023',
  'mar_2024','june_2024','sept_2024','dec_2024',
  'mar_2025','june_2025','sept_2025','dec_2025',
];

export const QUARTER_LABELS: Record<string, string> = {
  june_2020:'Jun 2020', sept_2020:'Sep 2020', dec_2020:'Dec 2020',
  june_2021:'Jun 2021', sept_2021:'Sep 2021', dec_2021:'Dec 2021',
  mar_2022:'Mar 2022', june_2022:'Jun 2022', sept_2022:'Sep 2022', dec_2022:'Dec 2022',
  mar_2023:'Mar 2023', june_2023:'Jun 2023', sept_2023:'Sep 2023', dec_2023:'Dec 2023',
  mar_2024:'Mar 2024', june_2024:'Jun 2024', sept_2024:'Sep 2024', dec_2024:'Dec 2024',
  mar_2025:'Mar 2025', june_2025:'Jun 2025', sept_2025:'Sep 2025', dec_2025:'Dec 2025',
};

export const QUARTER_FOLDERS: Record<string, string> = {
  june_2020:'2020-06', sept_2020:'2020-09', dec_2020:'2020-12',
  june_2021:'2021-06', sept_2021:'2021-09', dec_2021:'2021-12',
  mar_2022:'2022-03', june_2022:'2022-06', sept_2022:'2022-09', dec_2022:'2022-12',
  mar_2023:'2023-03', june_2023:'2023-06', sept_2023:'2023-09', dec_2023:'2023-12',
  mar_2024:'2024-03', june_2024:'2024-06', sept_2024:'2024-09', dec_2024:'2024-12',
  mar_2025:'2025-03', june_2025:'2025-06', sept_2025:'2025-09', dec_2025:'2025-12',
};

export function prettyCategoryName(cat: string): string {
  return cat.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
    .replace(/Acp /,'ACP ').replace(/Npa/,'NPA').replace(/Pmjdy/,'PMJDY')
    .replace(/Pmmy/,'PMMY').replace(/Msme/,'MSME').replace(/Kcc/,'KCC')
    .replace(/Shg/,'SHG').replace(/Jlg/,'JLG').replace(/Nrlm/,'NRLM')
    .replace(/Nulm/,'NULM').replace(/Pmegp/,'PMEGP').replace(/Sui/,'SUI')
    .replace(/Sc St/,'SC/ST').replace(/Pmay/,'PMAY').replace(/Fi /,'FI ')
    .replace(/Ldm/,'LDM').replace(/Rseti/,'RSETI').replace(/ Os$/,' O/S')
    .replace(/ Ps /,' PS ').replace(/ Ps$/,' PS').replace(/ Nps/,' NPS')
    .replace(/Dcc/,'DCC').replace(/Flc/,'FLC').replace(/Pmfme/,'PMFME')
    .replace(/Pmfby/,'PMFBY').replace(/Blbc/,'BLBC')
    .replace(/Aif/,'AIF').replace(/Apy/,'APY').replace(/Nlm/,'NLM')
    .replace(/Mudra/,'MUDRA').replace(/Sarfaesi/,'SARFAESI');
}
