export const CATEGORY_INFO: Record<string, string> = {
  aadhaar_authentication:              'Aadhaar-enabled transactions',
  acp_disbursement_agri:               'ACP disbursement - Agriculture',
  acp_disbursement_msme:               'ACP disbursement - MSME',
  acp_disbursement_non_ps:             'ACP disbursement - Non-Priority Sector',
  acp_disbursement_other_ps:           'ACP disbursement - Other Priority Sector',
  acp_npa_outstanding:                 'ACP NPA outstanding',
  acp_priority_sector_os_npa:          'Priority sector outstanding & NPA',
  acp_target_achievement:              'ACP targets vs achievement',
  agri_npa:                            'Agriculture NPA',
  agri_outstanding:                    'Agriculture outstanding',
  branch_network:                      'Bank branches, ATMs, CSPs',
  credit_deposit_ratio:                'Deposits, advances, CD ratio',
  crop_insurance:                      'Crop insurance (PMFBY)',
  dcc_meetings:                        'DCC/DLRC meetings',
  digital_transactions:                'Digital transactions (UPI, IMPS, BHIM)',
  education_loan:                      'Education loans',
  fi_kcc:                              'FI & KCC progress',
  flc_report:                          'Financial Literacy Centre report',
  fi_village_banking:                  'Village banking outlets',
  govt_sponsored_npa:                  'Government sponsored schemes NPA',
  housing_pmay:                        'Housing loans / PMAY',
  investment_credit_agri_disbursement: 'Investment credit (agri) - disbursement',
  investment_credit_agri_outstanding:  'Investment credit (agri) - outstanding',
  jlg:                                 'Joint Liability Groups',
  kcc:                                 'Kisan Credit Card',
  kcc_crop:                            'KCC crop-wise details',
  ldm_details:                         'Lead District Manager details',
  minority:                             'Lending to minorities',
  minority_disbursement:               'Lending to minorities - disbursement',
  minority_outstanding:                'Lending to minorities - outstanding',
  msme_npa:                            'MSME NPA',
  msme_outstanding:                    'MSME outstanding',
  non_ps_npa:                          'Non-Priority Sector NPA',
  non_ps_outstanding:                  'Non-Priority Sector outstanding',
  nrlm:                                'National Rural Livelihoods Mission',
  nulm:                                'National Urban Livelihoods Mission',
  other_ps_npa:                        'Other Priority Sector NPA',
  other_ps_outstanding:                'Other Priority Sector outstanding',
  pmegp:                               'PM Employment Generation Programme',
  pmjdy:                               'PM Jan Dhan Yojana',
  pmmy_mudra_disbursement:             'PMMY/Mudra disbursement',
  pmfme:                               'PM Formalisation of Micro Food Enterprises',
  pmmy_mudra_os_npa:                   'PMMY/Mudra outstanding & NPA',
  priority_sector_analysis:            'Priority sector lending analysis',
  recovery_bakijai:                    'Recovery & Bakijai',
  rseti:                               'Rural Self Employment Training',
  sc_st_finance:                       'Lending to SC/ST',
  shg:                                 'Self Help Groups',
  social_security:                     'Social security (PMSBY, PMJJBY, APY)',
  sui:                                 'Stand Up India',
  segregation_advances:                'Segregation of advances',
  tea_garden_labourers:                'Tea garden labourers',
  uncategorized:                       'Other / Uncategorized',
  weaker_section_os:                   'Weaker section lending',
  women_finance:                       'Lending to women',
  // West Bengal specific categories
  acp_priority_sector:                 'ACP Priority Sector targets & achievement',
  aif:                                 'Agriculture Infrastructure Fund',
  apy:                                 'Atal Pension Yojana',
  digital_payments:                    'Digital payments ecosystem',
  financial_literacy:                  'Financial Literacy Centres & camps',
  kcc_animal_husbandry:                'KCC Animal Husbandry',
  kcc_fishery:                         'KCC Fishery',
  mudra:                               'MUDRA loans (Shishu, Kishor, Tarun)',
  msme:                                'MSME clusters & credit linkage',
  nlm:                                 'National Livestock Mission',
  npa_recovery:                        'NPA & recovery position',
  sarfaesi:                            'SARFAESI recovery',
  shg_nrlm:                            'SHG credit linkage (NRLM)',
  shg_nulm:                            'SHG credit linkage (NULM)',
  social_security_schemes:             'Social security schemes (PMJJBY, PMSBY, APY)',
  svskp:                               'Swarnjayanti Gram Swarozgar Yojana',
  farm_sector:                         'Farm sector lending',
  non_farm_sector:                     'Non-farm sector lending',
  weaker_section:                      'Weaker section lending',
  housing_loan:                        'Housing loans',
  // Jharkhand specific categories
  acp_disbursement_agri_p2:            'ACP Agri disbursement (contd.)',
  acp_disbursement_non_ps:             'ACP Non-PS disbursement',
  acp_disbursement_non_ps_p2:          'ACP Non-PS disbursement (contd.)',
  acp_disbursement_other_ps_p2:        'ACP Other PS disbursement (contd.)',
  acp_disbursement_other_ps_p3:        'ACP Other PS disbursement (contd. 3)',
  ads_progress:                        'Advance Data System progress',
  agri_npa_p2:                         'Agriculture NPA (contd.)',
  business_correspondents:             'Business Correspondents',
  doubling_farmers_income:             'Doubling Farmers Income',
  doubling_farmers_income_p2:          'Doubling Farmers Income (contd.)',
  doubling_farmers_income_p3:          'Doubling Farmers Income (contd. 3)',
  govt_sponsored_npa:                  'Govt Sponsored Schemes NPA',
  guruji_credit_card:                  'Guruji Credit Card',
  investment_utilization:              'Investment / Place of Utilization',
  npa_recovery_p2:                     'NPA recovery (contd.)',
  other_ps_npa:                        'Other Priority Sector NPA',
  pm_svanidhi:                         'PM SVANidhi',
  pm_svanidhi_p2:                      'PM SVANidhi (contd.)',
  pm_vishwakarma:                      'PM Vishwakarma',
  pmmy_mudra_disbursement:             'PMMY/Mudra disbursement',
  pmmy_mudra_os_npa:                   'PMMY/Mudra O/S & NPA',
  priority_sector_npa:                 'Priority Sector NPA',
  priority_sector_outstanding:         'Priority Sector outstanding',
  recovery_certificate:                'Certificate Cases recovery',
  recovery_drt:                        'DRT Cases recovery',
  rseti_p2:                            'RSETI (contd.)',
  sc_st_finance_p2:                    'SC/ST finance (contd.)',
  shg_p2:                              'SHG (contd.)',
  shg_p3:                              'SHG (contd. 3)',
  women_finance_p2:                    'Women finance (contd.)',
  // Odisha specific categories
  acp_district_agri:                   'ACP District-wise Agriculture',
  acp_district_agri_allied:            'ACP District-wise Agri & Allied',
  acp_district_ancillary:              'ACP District-wise Ancillary',
  acp_district_msme:                   'ACP District-wise MSME',
  acp_district_total:                  'ACP District-wise Total',
  bharatnet:                           'BharatNet connectivity',
  bharatnet_p2:                        'BharatNet (contd.)',
  bharatnet_p3:                        'BharatNet (contd. 3)',
  bharatnet_p4:                        'BharatNet (contd. 4)',
  branch_network_p2:                   'Branch network (contd.)',
  branch_network_p3:                   'Branch network (contd. 3)',
  branch_network_p4:                   'Branch network (contd. 4)',
  cgtmse:                              'CGTMSE coverage',
  cgtmse_p2:                           'CGTMSE (contd.)',
  cm_srim:                             'CM SRIM scheme',
  digital_coverage_business:           'Digital coverage - business accounts',
  digital_coverage_savings:            'Digital coverage - savings accounts',
  digital_coverage_savings_p2:         'Digital coverage - savings (contd.)',
  digital_coverage_savings_p3:         'Digital coverage - savings (contd. 3)',
  digital_coverage_savings_p4:         'Digital coverage - savings (contd. 4)',
  district_misc:                       'District miscellaneous data',
  key_indicators:                      'Key indicators (CD ratio, deposits, advances)',
  npa:                                 'Non-Performing Assets',
  pm_surya_ghar:                       'PM Surya Ghar',
  pmjdy_p2:                            'PMJDY (contd.)',
  pmjdy_p3:                            'PMJDY (contd. 3)',
  pmjdy_p4:                            'PMJDY (contd. 4)',
  rseti_p3:                            'RSETI (contd. 3)',
  rseti_p4:                            'RSETI (contd. 4)',
  rseti_p5:                            'RSETI (contd. 5)',
  rseti_p6:                            'RSETI (contd. 6)',
  social_security_claims:              'Social security claims',
  stand_up_india:                      'Stand Up India',
  stand_up_india_p2:                   'Stand Up India (contd.)',
  suy:                                 'SUY scheme',
  town_hall_msme:                      'Town Hall MSME',
};

export const QUARTER_ORDER = [
  'june_2020','sept_2020','dec_2020',
  'june_2021','sept_2021','dec_2021',
  'mar_2022','june_2022','sept_2022','dec_2022',
  'mar_2023','june_2023','sept_2023','dec_2023',
  'mar_2024','june_2024','sept_2024','dec_2024',
  'mar_2025','june_2025','sept_2025','dec_2025',
];

export const QUARTER_LABELS: Record<string, string> = {
  june_2020:'Jun 2020', sept_2020:'Sep 2020', dec_2020:'Dec 2020',
  june_2021:'Jun 2021', sept_2021:'Sep 2021', dec_2021:'Dec 2021',
  mar_2022:'Mar 2022', june_2022:'Jun 2022', sept_2022:'Sep 2022', dec_2022:'Dec 2022',
  mar_2023:'Mar 2023', june_2023:'Jun 2023', sept_2023:'Sep 2023', dec_2023:'Dec 2023',
  mar_2024:'Mar 2024', june_2024:'Jun 2024', sept_2024:'Sep 2024', dec_2024:'Dec 2024',
  mar_2025:'Mar 2025', june_2025:'Jun 2025', sept_2025:'Sep 2025', dec_2025:'Dec 2025',
};

export const QUARTER_FOLDERS: Record<string, string> = {
  june_2020:'2020-06', sept_2020:'2020-09', dec_2020:'2020-12',
  june_2021:'2021-06', sept_2021:'2021-09', dec_2021:'2021-12',
  mar_2022:'2022-03', june_2022:'2022-06', sept_2022:'2022-09', dec_2022:'2022-12',
  mar_2023:'2023-03', june_2023:'2023-06', sept_2023:'2023-09', dec_2023:'2023-12',
  mar_2024:'2024-03', june_2024:'2024-06', sept_2024:'2024-09', dec_2024:'2024-12',
  mar_2025:'2025-03', june_2025:'2025-06', sept_2025:'2025-09', dec_2025:'2025-12',
};

export function prettyCategoryName(cat: string): string {
  return cat.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
    .replace(/Acp /,'ACP ').replace(/Npa/,'NPA').replace(/Pmjdy/,'PMJDY')
    .replace(/Pmmy/,'PMMY').replace(/Msme/,'MSME').replace(/Kcc/,'KCC')
    .replace(/Shg/,'SHG').replace(/Jlg/,'JLG').replace(/Nrlm/,'NRLM')
    .replace(/Nulm/,'NULM').replace(/Pmegp/,'PMEGP').replace(/Sui/,'SUI')
    .replace(/Sc St/,'SC/ST').replace(/Pmay/,'PMAY').replace(/Fi /,'FI ')
    .replace(/Ldm/,'LDM').replace(/Rseti/,'RSETI').replace(/ Os$/,' O/S')
    .replace(/ Ps /,' PS ').replace(/ Ps$/,' PS').replace(/ Nps/,' NPS')
    .replace(/Dcc/,'DCC').replace(/Flc/,'FLC').replace(/Pmfme/,'PMFME')
    .replace(/Pmfby/,'PMFBY').replace(/Blbc/,'BLBC')
    .replace(/Aif/,'AIF').replace(/Apy/,'APY').replace(/Nlm/,'NLM')
    .replace(/Mudra/,'MUDRA').replace(/Sarfaesi/,'SARFAESI');
}
