<script>
  import { onMount } from 'svelte';

  let allSummaries = $state([]);
  let loading = $state(true);

  const base = typeof window !== 'undefined' && window.__FINER_BASE ? window.__FINER_BASE : '/';

  const STATES = [
    { slug: 'assam', name: 'Assam', color: '#b8603e' },
    { slug: 'meghalaya', name: 'Meghalaya', color: '#3d7a8e' },
    { slug: 'manipur', name: 'Manipur', color: '#5a7a3a' },
    { slug: 'mizoram', name: 'Mizoram', color: '#8b6914' },
    { slug: 'nagaland', name: 'Nagaland', color: '#7a5095' },
    { slug: 'arunachal-pradesh', name: 'Arunachal Pradesh', color: '#c44830' },
  ];

  const MONTH_ORDER = { March: 3, June: 6, September: 9, December: 12, Unknown: 0 };

  function quarterSortKey(q) {
    const parts = q.split(' ');
    if (parts.length === 2) return parseInt(parts[1]) * 100 + (MONTH_ORDER[parts[0]] || 0);
    return 0;
  }

  let selectedState = $state('assam');
  let selectedQuarter = $state('');

  // Quarters available for the selected state, sorted latest-first
  let stateQuarters = $derived.by(() => {
    return allSummaries
      .filter(s => s.state_slug === selectedState)
      .sort((a, b) => quarterSortKey(b.quarter) - quarterSortKey(a.quarter))
      .map(s => s.quarter);
  });

  // Auto-select latest quarter when state changes
  $effect(() => {
    if (stateQuarters.length > 0 && !stateQuarters.includes(selectedQuarter)) {
      selectedQuarter = stateQuarters[0];
    }
  });

  // The selected summary item
  let item = $derived(
    allSummaries.find(s => s.state_slug === selectedState && s.quarter === selectedQuarter)
  );

  let stateColor = $derived(
    STATES.find(s => s.slug === selectedState)?.color || '#b8603e'
  );

  let stateCount = $derived(
    allSummaries.filter(s => s.state_slug === selectedState).length
  );

  onMount(async () => {
    try {
      const res = await fetch(`${base}slbc-data/ne-meeting-summaries.json`);
      if (res.ok) {
        const data = await res.json();
        allSummaries = data.summaries || [];
      }
    } catch (e) {
      console.error('Failed to load meeting summaries:', e);
    } finally {
      loading = false;
    }
  });
</script>

<div class="summaries-section">
  {#if loading}
    <div class="loading">Loading summaries...</div>
  {:else if allSummaries.length === 0}
    <div class="loading">No summaries available yet.</div>
  {:else}
    <!-- Controls row -->
    <div class="controls">
      <div class="control-group">
        <label class="control-label" for="state-select">State</label>
        <select id="state-select" class="dropdown" bind:value={selectedState}>
          {#each STATES as st}
            {@const count = allSummaries.filter(s => s.state_slug === st.slug).length}
            <option value={st.slug}>{st.name} ({count})</option>
          {/each}
        </select>
      </div>

      <div class="control-group">
        <label class="control-label" for="quarter-select">Quarter</label>
        <select id="quarter-select" class="dropdown" bind:value={selectedQuarter}>
          {#each stateQuarters as q}
            <option value={q}>{q}</option>
          {/each}
        </select>
      </div>

      <div class="stat-badge">
        <span class="stat-num">{stateCount}</span>
        <span class="stat-text">meetings</span>
      </div>
    </div>

    <!-- Single large card -->
    {#if item}
      <div class="meeting-card" style="border-top: 4px solid {stateColor}">
        <!-- Card header -->
        <div class="card-header">
          <div class="card-title-row">
            <h2 class="card-quarter">{item.quarter}</h2>
            <a class="download-btn" href={item.pdf_url} target="_blank" rel="noopener">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
              Download Minutes PDF
            </a>
          </div>
          <div class="card-meta">
            <span class="meta-filename">{item.filename}</span>
            {#if item.pages > 0}
              <span class="meta-sep">&middot;</span>
              <span class="meta-pages">{item.pages} pages</span>
            {/if}
          </div>
        </div>

        <!-- Summary body -->
        <div class="card-body">
          {@html item.summary
            .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
            .replace(/\n/g, '<br>')}
        </div>

        <!-- Card footer -->
        <div class="card-footer">
          <span class="ai-note">Summary generated by AI</span>
        </div>
      </div>
    {:else}
      <div class="empty">No summary available for this selection.</div>
    {/if}
  {/if}
</div>

<style>
  .summaries-section {
    padding-top: 8px;
  }
  .loading, .empty {
    font-family: var(--font-sans, Inter, sans-serif);
    font-size: 12px;
    color: var(--muted, #888078);
    padding: 24px 0;
  }

  /* Controls */
  .controls {
    display: flex;
    align-items: flex-end;
    gap: 16px;
    margin-bottom: 24px;
    flex-wrap: wrap;
  }
  .control-group {
    display: flex;
    flex-direction: column;
    gap: 4px;
  }
  .control-label {
    font-family: var(--font-sans, Inter, sans-serif);
    font-size: 9px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: var(--label, #aaa09a);
  }
  .dropdown {
    font-family: var(--font-sans, Inter, sans-serif);
    font-size: 13px;
    font-weight: 500;
    color: var(--text, #1a1410);
    background: #fff;
    border: 1px solid var(--border, #e8e5e0);
    border-radius: 8px;
    padding: 8px 32px 8px 12px;
    appearance: none;
    background-image: url("data:image/svg+xml,%3Csvg width='10' height='6' viewBox='0 0 10 6' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M1 1L5 5L9 1' stroke='%23aaa09a' stroke-width='1.5' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E");
    background-repeat: no-repeat;
    background-position: right 10px center;
    cursor: pointer;
    min-width: 180px;
    transition: border-color 0.2s;
  }
  .dropdown:hover {
    border-color: #d0cdc8;
  }
  .dropdown:focus {
    outline: none;
    border-color: var(--accent, #b8603e);
  }

  .stat-badge {
    display: flex;
    align-items: baseline;
    gap: 4px;
    padding: 8px 0;
    margin-left: auto;
  }
  .stat-num {
    font-family: 'IBM Plex Mono', monospace;
    font-size: 22px;
    font-weight: 700;
    color: var(--text, #1a1410);
  }
  .stat-text {
    font-family: var(--font-sans, Inter, sans-serif);
    font-size: 10px;
    color: var(--muted, #888078);
  }

  /* Meeting card */
  .meeting-card {
    background: #fff;
    border: 1px solid var(--border, #e8e5e0);
    border-radius: 12px;
    overflow: hidden;
  }

  .card-header {
    padding: 24px 28px 16px;
    border-bottom: 1px solid rgba(232, 229, 224, 0.5);
  }
  .card-title-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 16px;
    margin-bottom: 6px;
  }
  .card-quarter {
    font-family: 'Playfair Display', Georgia, serif;
    font-size: 24px;
    font-weight: 700;
    color: var(--text, #1a1410);
    letter-spacing: -0.01em;
    margin: 0;
  }

  .download-btn {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    font-family: var(--font-sans, Inter, sans-serif);
    font-size: 11px;
    font-weight: 600;
    color: #fff;
    background: var(--text, #1a1410);
    text-decoration: none;
    padding: 8px 16px;
    border-radius: 6px;
    transition: all 0.2s;
    white-space: nowrap;
    flex-shrink: 0;
  }
  .download-btn:hover {
    background: var(--accent, #b8603e);
  }

  .card-meta {
    display: flex;
    align-items: center;
    gap: 6px;
  }
  .meta-filename {
    font-family: var(--font-sans, Inter, sans-serif);
    font-size: 11px;
    color: var(--label, #aaa09a);
  }
  .meta-sep {
    color: var(--label, #aaa09a);
    font-size: 10px;
  }
  .meta-pages {
    font-family: var(--font-sans, Inter, sans-serif);
    font-size: 11px;
    color: var(--label, #aaa09a);
  }

  /* Card body */
  .card-body {
    padding: 24px 28px;
    font-family: Georgia, serif;
    font-size: 14px;
    line-height: 1.8;
    color: var(--text, #1a1410);
    min-height: 200px;
  }
  .card-body :global(strong) {
    font-weight: 700;
    color: var(--text, #1a1410);
  }

  /* Card footer */
  .card-footer {
    padding: 14px 28px;
    border-top: 1px solid rgba(232, 229, 224, 0.5);
    display: flex;
    align-items: center;
    justify-content: space-between;
    background: rgba(245, 244, 241, 0.3);
  }
  .ai-note {
    font-family: var(--font-sans, Inter, sans-serif);
    font-size: 9px;
    color: var(--label, #aaa09a);
    font-style: italic;
  }

  @media (max-width: 640px) {
    .controls { flex-direction: column; align-items: stretch; }
    .dropdown { min-width: unset; width: 100%; }
    .stat-badge { margin-left: 0; }
    .card-header { padding: 18px 20px 12px; }
    .card-title-row { flex-direction: column; align-items: flex-start; gap: 10px; }
    .card-body { padding: 18px 20px; font-size: 13px; }
    .card-footer { padding: 12px 20px; flex-direction: column; gap: 8px; align-items: flex-start; }
    .card-quarter { font-size: 20px; }
  }
</style>
